### ISSUE TITLE
cant export Fjäderholmarna

### ISSUE THREAD

**Issue by Fusselwurm** [gruppe-adler/grad_meh#31]
https://steamcommunity.com/sharedfiles/filedetails/?id=807130445

11:55:55 "[GRAD_MEH]: Error while exporting map fjaderholmarna: Couldn't export map, because the PBO of WRP couldn't be found. (Most likely because it is a EBO)"

when Fjäderholmarna is loaded, this value exists: 
`configWorlds >> "fjaderholmarna" >> worldName = "\fjaderholmarna\smurks\fjaderholmarna.wrp";`

also the wrp path exists in the pbo:

![Unbenannt](https://user-images.githubusercontent.com/52833/155309410-7a254810-4f43-4605-ab04-7933dbeeb194.png)

need a more detailed explanation of whats going on.

**Comment by TheWillard** [comment]
The map export is failing because of an empty prefix in the pbo and unbinarized rvmats. Both Issues are not easily fixable at the moment in `grad_aff`. With a few workarounds, I managed to export everything except the sat images. I pushed the files to https://github.com/gruppe-adler/meh-data/tree/fjaederholmarna/fjaderholmarna

**Comment by Fusselwurm** [comment]
:frowning: :trollface: version field in meta.json [must be a number](https://github.com/gruppe-adler/grad_meh/blob/master/docs/metajson_spec.md) but in that branch its a string.

**Comment by DerZade** [comment]
I agree. semver ftw 🙌
